### PR TITLE
Add defaultDotColor game config property.

### PR DESCRIPTION
**Pull request by graphnode**
Added requested feature in issue #6 to change the default clear color.
Should be backwards compatible since it uses Color.GREY by default.

### CODE REVIEW

**Comment by Givup** [comment]
Should all mentions to "Color.GREY" be changed to "Color.Gray"?

**Comment by jamesroutley** [comment]
Hi @graphnode thank you very much for taking the time to add this! As mentioned in #6, would you mind changing `clearColor` to `defaultDotColor`? I think it's a bit more descriptive, and it means users of the engine don't need to know about how the engine clears the screen on each frame.

**Comment by graphnode** [comment]
> Should all mentions to "Color.GREY" be changed to "Color.Gray"?

Yes, it should be Gr**a**y but it's capitalized because that is how the color names are.

**Comment by graphnode** [comment]
Ok, renamed the property and fixed the comment.

**Review by jamesroutley — APPROVED** [review]
Looks great! Thanks for adding this

**Pull request merged**
